### ISSUE TITLE
Latest bundle loader causing webpack errors

### ISSUE THREAD

**Issue by akshayp** [webpack/bundle-loader#14]
@sokra From 0.5.4 our webpack build started failing with the following error

```
Fatal error: AsyncDependenciesBlock is not defined
```

**Comment by sokra** [comment]
Not sure why... Do you have a stack trace?

**Comment by akshayp** [comment]
Thanks for fixing so quickly @sokra!

**Comment by roderickhsiao** [comment]
Thanks @akshayp , checking the same thing :)

**Comment by roderickhsiao** [comment]
and @sokra thanks :)
